services:
  transcriber:
    image: ghcr.io/readtedium/easy-transcriber:latest
    build: .
    env_file: ".env"
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./uploads:/app/uploads
      - ./media:/app/media
      - ./data:/app/data
    restart: unless-stopped